// RU lang variables UTF-8
tinyMCE.addI18n({ru: { fullpage : {

	title : 'Свойства документа',
	desc : 'Свойства документа',
	meta_tab : 'Основные',
	appearance_tab : 'Видимость',
	advanced_tab : 'Дополнительные',
	meta_props : 'Мета информация',
	langprops : 'Язык и кодировка',
	meta_title : 'Название',
	meta_keywords : 'Ключевые слова',
	meta_description : 'Описание',
	meta_robots : 'Роботы',
	doctypes : 'Тип документа (Doctype)',
	langcode : 'Код языка',
	langdir : 'Направление языка',
	ltr : 'Слева направо',
	rtl : 'Справа налево',
	xml_pi : 'XML декларация',
	encoding : 'Кодировка',
	appearance_bgprops : 'Свойства фона',
	appearance_marginprops : 'Отступы',
	appearance_linkprops : 'Цвет ссылок',
	appearance_textprops : 'Свойства текста',
	bgcolor : 'Цвет фона',
	bgimage : 'Фоновое изображение',
	left_margin : 'Отступ слева',
	right_margin : 'Отступ справа',
	top_margin : 'Отступ сверху',
	bottom_margin : 'Отступ снизу',
	text_color : 'Цвет текста',
	font_size : 'Размер шрифта',
	font_face : 'Шрифт',
	link_color : 'Цвет ссылки',
	hover_color : 'Цвет при наведении на ссылку',
	visited_color : 'Цвет посещенной ссылки',
	active_color : 'Цвет активной ссылки',
	textcolor : 'Цвет',
	fontsize : 'Размер шрифта',
	fontface : 'Тип шрифта',
	meta_index_follow : 'Индексировать и следовать по ссылкам',
	meta_index_nofollow : 'Индексировать и не следовать по ссылкам',
	meta_noindex_follow : 'Не индексировать, но следовать по ссылкам',
	meta_noindex_nofollow : 'Не индексировать и не следовать по ссылкам',
	appearance_style : 'Таблица стилей и свойства стиля',
	stylesheet : 'Таблица стилей',
	style : 'Стиль',
	author : 'Автор',
	copyright : 'Авторское право',
	add : 'Добавить новый элемент',
	remove : 'Удалить выделенный элемент',
	moveup : 'Переместить выбранный элемент вверх',
	movedown : 'Переместить выделенный элемент вниз',
	head_elements : 'Элемент главный',
	info : 'Информация',
	info_text : '',
	add_title : 'Элемент название',
	add_meta : 'Элемент мета',
	add_script : 'Элемент скрипт',
	add_style : 'Элемент стиль',
	add_link : 'Элемент ссылка',
	add_base : 'Элемент базовый',
	add_comment : 'Элемент комментарий',
	title_element : 'Элемент название',
	script_element : 'Элемент скрипт',
	style_element : 'Элемент стиль',
	base_element : 'Элемент базовый',
	link_element : 'Элемент ссылка',
	meta_element : 'Элемент мета',
	comment_element : 'Комментарий',
	src : 'Источник',
	language : 'Язык',
	href : 'Href',
	target : 'Цель',
	rel : 'Вып',
	type : 'Тип',
	charset : 'Кодировка',
	defer : 'Задержка',
	media : 'Медиа',
	properties : 'Свойства',
	name : 'Имя',
	value : 'Значение',
	content : 'Контент',
	rel : 'Вып',
	rev : 'Обр',
	hreflang : 'Href язык',
	general_props : 'Основные',
	advanced_props : 'Дополнительные',
	delta_width : 0,
	delta_height : 0
}}});


tinyMCE.addI18n('ru.fullpage_dlg',{
    title:"Document properties",
    meta_tab:"General",
    appearance_tab:"Appearance",
    advanced_tab:"Advanced",
    meta_props:"Meta information",
    langprops:"Language and encoding",
    meta_title:"Title",
    meta_keywords:"Keywords",
    meta_description:"Description",
    meta_robots:"Robots",
    doctypes:"Doctype",
    langcode:"Language code",
    langdir:"Language direction",
    ltr:"Left to right",
    rtl:"Right to left",
    xml_pi:"XML declaration",
    encoding:"Character encoding",
    appearance_bgprops:"Background properties",
    appearance_marginprops:"Body margins",
    appearance_linkprops:"Link colors",
    appearance_textprops:"Text properties",
    bgcolor:"Background color",
    bgimage:"Background image",
    left_margin:"Left margin",
    right_margin:"Right margin",
    top_margin:"Top margin",
    bottom_margin:"Bottom margin",
    text_color:"Text color",
    font_size:"Font size",
    font_face:"Font face",
    link_color:"Link color",
    hover_color:"Hover color",
    visited_color:"Visited color",
    active_color:"Active color",
    textcolor:"Color",
    fontsize:"Font size",
    fontface:"Font family",
    meta_index_follow:"Index and follow the links",
    meta_index_nofollow:"Index and don't follow the links",
    meta_noindex_follow:"Do not index but follow the links",
    meta_noindex_nofollow:"Do not index and don\'t follow the links",
    appearance_style:"Stylesheet and style properties",
    stylesheet:"Stylesheet",
    style:"Style",
    author:"Author",
    copyright:"Copyright",
    add:"Add new element",
    remove:"Remove selected element",
    moveup:"Move selected element up",
    movedown:"Move selected element down",
    head_elements:"Head elements",
    info:"Information",
    add_title:"Title element",
    add_meta:"Meta element",
    add_script:"Script element",
    add_style:"Style element",
    add_link:"Link element",
    add_base:"Base element",
    add_comment:"Comment node",
    title_element:"Title element",
    script_element:"Script element",
    style_element:"Style element",
    base_element:"Base element",
    link_element:"Link element",
    meta_element:"Meta element",
    comment_element:"Comment",
    src:"Src",
    language:"Language",
    href:"Href",
    target:"Target",
    type:"Type",
    charset:"Charset",
    defer:"Defer",
    media:"Media",
    properties:"Properties",
    name:"Name",
    value:"Value",
    content:"Content",
    rel:"Rel",
    rev:"Rev",
    hreflang:"Href lang",
    general_props:"General",
    advanced_props:"Advanced"
});