// RU lang variables UTF-8
tinyMCE.addI18n({ru: { table : {
general_tab : 'Основные',
advanced_tab : 'Расширенные',
general_props : 'Основные свойства',
advanced_props : 'Расширенные свойства',
desc : 'Вставить новую таблицу',
row_before_desc : 'Вставить строку перед',
row_after_desc : 'Вставить строку после',
delete_row_desc : 'Удалить строку',
col_before_desc : 'Вставить колонку перед',
col_after_desc : 'Вставить колонку после',
delete_col_desc : 'Удалить колонку',
rowtype : 'Строка в части таблицы',
title : 'Вставить/Изменить таблицу',
width : 'Ширина',
height : 'Высота',
cols : 'Колонки',
rows : 'Строки',
cellspacing : 'Расстояние между ячейками',
cellpadding : 'Отступ в ячейках',
border : 'Граница',
align : 'Выравнивание',
align_default : 'По-умолчанию',
align_left : 'Всево',
align_right : 'Вправо',
align_middle : 'По центру',
row_title : 'Свойства строки таблицы',
cell_title : 'Свойства ячейки таблицы',
cell_type : 'Тип ячейки',
row_desc : 'Свойства строки таблицы',
cell_desc : 'Свойства ячейки таблицы',
valign : 'Вертикальное выравнивание',
align_top : 'По верху',
align_bottom : 'По низу',
props_desc : 'Свойства таблицы',
bordercolor : 'Цвет рамки',
bgcolor : 'Цвет фона',
merge_cells_title : 'Объединить ячейки таблицы',
split_cells_desc : 'Разделить ячейки таблицы',
merge_cells_desc : 'Объединить ячейки таблицы',
cut_row_desc : 'Вылезать строку таблицы',
copy_row_desc : 'Скопировать строку таблицы',
paste_row_before_desc : 'Вставить строку таблицы перед',
paste_row_after_desc : 'Вставить строку таблицы после',
id : 'Ид',
style: 'Стиль',
langdir : 'Описание языка',
langcode : 'Код языка',
mime : 'Целевой MIME тип',
ltr : 'Слева направо',
rtl : 'Справа налево',
bgimage : 'Фоновое изображение',
summary : 'Краткое описание',
td : "Тело",
th : "Заголовок",
cell_cell : 'Обновить текущую ячейку',
cell_row : 'Обновить текущую строку',
cell_all : 'Обновить все ячейки в таблице',
row_row : 'Обновить текущую строку',
row_odd : 'Обновить нечетные строки в таблице',
row_even : 'Обновить четные строки в таблице',
row_all : 'Обновить все строки в таблице',
thead : 'Заголовок таблицы',
tbody : 'Тело таблицы',
tfoot : 'Футер таблицы',
del : 'Удалить таблицу',
scope : 'Границы',
row : 'Строка',
col : 'Колонка',
rowgroup : 'Группа строк',
colgroup : 'Группа колонок',
col_limit : 'Вы превысили максимально допустимое количество колонок - {$cols}.',
row_limit : 'Вы превысили максимально допустимое количество строк - {$rows}.',
cell_limit : 'Вы превысили максимально допустимое количество ячеек -  {$cells}.',
missing_scope: 'Вы уверены, что хотите продолжать не обозначив границы ячеек шапки таблицы? Без этого, возможно, некоторым пользователям будет затруднительно понять, что за данные находятся в таблице.'
}}});


tinyMCE.addI18n('ru.table_dlg',{
    general_tab:"General",
    advanced_tab:"Advanced",
    general_props:"General properties",
    advanced_props:"Advanced properties",
    rowtype:"Row in table part",
    title:"Insert/Modify table",
    width:"Width",
    height:"Height",
    cols:"Cols",
    rows:"Rows",
    cellspacing:"Cellspacing",
    cellpadding:"Cellpadding",
    border:"Border",
    align:"Alignment",
    align_default:"Default",
    align_left:"Left",
    align_right:"Right",
    align_middle:"Center",
    row_title:"Table row properties",
    cell_title:"Table cell properties",
    cell_type:"Cell type",
    valign:"Vertical alignment",
    align_top:"Top",
    align_bottom:"Bottom",
    bordercolor:"Border color",
    bgcolor:"Background color",
    merge_cells_title:"Merge table cells",
    id:"Id",
    style:"Style",
    langdir:"Language direction",
    langcode:"Language code",
    mime:"Target MIME type",
    ltr:"Left to right",
    rtl:"Right to left",
    bgimage:"Background image",
    summary:"Summary",
    td:"Data",
    th:"Header",
    cell_cell:"Update current cell",
    cell_row:"Update all cells in row",
    cell_all:"Update all cells in table",
    row_row:"Update current row",
    row_odd:"Update odd rows in table",
    row_even:"Update even rows in table",
    row_all:"Update all rows in table",
    thead:"Table Head",
    tbody:"Table Body",
    tfoot:"Table Foot",
    scope:"Scope",
    rowgroup:"Row Group",
    colgroup:"Col Group",
    col_limit:"You've exceeded the maximum number of columns of {$cols}.",
    row_limit:"You've exceeded the maximum number of rows of {$rows}.",
    cell_limit:"You've exceeded the maximum number of cells of {$cells}.",
    missing_scope:"Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.",
    caption:"Table caption",
    frame:"Frame",
    frame_none:"none",
    frame_groups:"groups",
    frame_rows:"rows",
    frame_cols:"cols",
    frame_all:"all",
    rules:"Rules",
    rules_void:"void",
    rules_above:"above",
    rules_below:"below",
    rules_hsides:"hsides",
    rules_lhs:"lhs",
    rules_rhs:"rhs",
    rules_vsides:"vsides",
    rules_box:"box",
    rules_border:"border"
});
