// RU lang variables UTF-8
tinyMCE.addI18n({ru: { media: {
    title : 'Вставить / редактировать медиа',
    desc : 'Вставить / редактировать медиа',
    general : 'Основной',
    advanced : 'Дополнительный',
    file : 'Файл',
    list : 'Список',
    size : 'Размеры',
    preview : 'Предпросмотр',
    constrain_proportions : 'Поддерживать пропорции',
    type : 'Тип',
    id : 'Ид',
    name : 'Имя',
    class_name : 'Класс',
    vspace : 'V-Отступ',
    hspace : 'H-Отступ',
    play : 'Авто проигрывание',
    loop : 'Цикл',
    menu : 'Показать меню',
    quality : 'Качество',
    scale : 'Масштаб',
    align : 'Выравнивание',
    salign : 'S-Выравнивание',
    wmode : 'W-Режим',
    bgcolor : 'Фон',
    base : 'База',
    flashvars : 'Переменные флеш',
    liveconnect : 'SWLiveConnect',
    autohref : 'Авто Ссылка',
    cache : 'Кеш',
    hidden : 'Скрытый',
    controller : 'Контроллер',
    kioskmode : 'Режим Kiosk',
    playeveryframe : 'Проигрывать каждый кадр',
    targetcache : 'Целевой кеш',
    correction : 'No correction',
    enablejavascript : 'Включить JavaScript',
    starttime : 'Время начала',
    endtime : 'Время окончания',
    href : 'Ссылка',
    qtsrcchokespeed : 'Уменьшить скорость',
    target : 'Цель',
    volume : 'Громкость',
    autostart : 'Авто запуск',
    enabled : 'Включено',
    fullscreen : 'Полный экран',
    invokeurls : 'Активизировать ссылки',
    mute : 'Тишина',
    stretchtofit : 'Растянуть до вхождения',
    windowlessvideo : 'Безоконное видео',
    balance : 'Баланс',
    baseurl : 'Базовая ссылка',
    captioningid : 'Ид ввода субтитров',
    currentmarker : 'Текущая отметка',
    currentposition : 'Текущая позиция',
    defaultframe : 'Кадр по умолчанию',
    playcount : 'Счетчик',
    rate : 'Частота',
    uimode : 'UI режим',
    flash_options : 'Опции Флеш',
    qt_options : 'Опции Quicktime',
    wmp_options : 'Опции проигрывателя Windows media',
    rmp_options : 'Опции проигрывателя Real media',
    shockwave_options : 'Опции Shockwave',
    autogotourl : 'Авто переход по ссылке',
    center : 'Центр',
    imagestatus : 'Статус изображения',
    maintainaspect : 'Поддерживать аспект',
    nojava : 'Без java',
    prefetch : 'Упреждение',
    shuffle : 'Перемешать',
    console : 'Консоль',
    numloop : 'Количество циклов',
    controls : 'Управления',
    scriptcallbacks : 'Обратный вызов скрипта',
    swstretchstyle : 'Стиль растяжения',
    swstretchhalign : 'H-Выравнивание растяжения',
    swstretchvalign : 'V-Выравнивание растяжения',
    sound : 'Звук',
    progress : 'Прогресс',
    qtsrc : 'QT Исх',
    qt_stream_warn : 'Потоковые rtsp ресурсы должны быть добавлены в поле QT Исх в дополнительную графу.\nВы также должны добавить не потоковую версию в поле Исх..'
}}});


tinyMCE.addI18n('ru.media_dlg',{
    title:"Insert / edit embedded media",
    general:"General",
    advanced:"Advanced",
    file:"File/URL",
    list:"List",
    size:"Dimensions",
    preview:"Preview",
    constrain_proportions:"Constrain proportions",
    type:"Type",
    id:"Id",
    name:"Name",
    class_name:"Class",
    vspace:"V-Space",
    hspace:"H-Space",
    play:"Auto play",
    loop:"Loop",
    menu:"Show menu",
    quality:"Quality",
    scale:"Scale",
    align:"Align",
    salign:"SAlign",
    wmode:"WMode",
    bgcolor:"Background",
    base:"Base",
    flashvars:"Flashvars",
    liveconnect:"SWLiveConnect",
    autohref:"AutoHREF",
    cache:"Cache",
    hidden:"Hidden",
    controller:"Controller",
    kioskmode:"Kiosk mode",
    playeveryframe:"Play every frame",
    targetcache:"Target cache",
    correction:"No correction",
    enablejavascript:"Enable JavaScript",
    starttime:"Start time",
    endtime:"End time",
    href:"Href",
    qtsrcchokespeed:"Choke speed",
    target:"Target",
    volume:"Volume",
    autostart:"Auto start",
    enabled:"Enabled",
    fullscreen:"Fullscreen",
    invokeurls:"Invoke URLs",
    mute:"Mute",
    stretchtofit:"Stretch to fit",
    windowlessvideo:"Windowless video",
    balance:"Balance",
    baseurl:"Base URL",
    captioningid:"Captioning id",
    currentmarker:"Current marker",
    currentposition:"Current position",
    defaultframe:"Default frame",
    playcount:"Play count",
    rate:"Rate",
    uimode:"UI Mode",
    flash_options:"Flash options",
    qt_options:"Quicktime options",
    wmp_options:"Windows media player options",
    rmp_options:"Real media player options",
    shockwave_options:"Shockwave options",
    autogotourl:"Auto goto URL",
    center:"Center",
    imagestatus:"Image status",
    maintainaspect:"Maintain aspect",
    nojava:"No java",
    prefetch:"Prefetch",
    shuffle:"Shuffle",
    console:"Console",
    numloop:"Num loops",
    controls:"Controls",
    scriptcallbacks:"Script callbacks",
    swstretchstyle:"Stretch style",
    swstretchhalign:"Stretch H-Align",
    swstretchvalign:"Stretch V-Align",
    sound:"Sound",
    progress:"Progress",
    qtsrc:"QT Src",
    qt_stream_warn:"Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..",
    align_top:"Top",
    align_right:"Right",
    align_bottom:"Bottom",
    align_left:"Left",
    align_center:"Center",
    align_top_left:"Top left",
    align_top_right:"Top right",
    align_bottom_left:"Bottom left",
    align_bottom_right:"Bottom right",
    flv_options:"Flash video options",
    flv_scalemode:"Scale mode",
    flv_buffer:"Buffer",
    flv_startimage:"Start image",
    flv_starttime:"Start time",
    flv_defaultvolume:"Default volumne",
    flv_hiddengui:"Hidden GUI",
    flv_autostart:"Auto start",
    flv_loop:"Loop",
    flv_showscalemodes:"Show scale modes",
    flv_smoothvideo:"Smooth video",
    flv_jscallback:"JS Callback"
});