// RU lang variables UTF-8
tinyMCE.addI18n({ru: { xhtmlxtras : {
cite_desc : 'Цитирование',
abbr_desc : 'Аббревиатура',
acronym_desc : 'Акроним',
del_desc : 'Стирание',
ins_desc : 'Вставка',
attribute_label_title : 'Заголовок',
attribute_label_id : 'ИД',
attribute_label_class : 'Класс',
attribute_label_style : 'Стиль',
attribute_label_cite : 'Цитировать',
attribute_label_datetime : 'Дата/Время',
attribute_label_langdir : 'Направление Текста',
attribute_option_ltr : 'Слева направо',
attribute_option_rtl : 'Справа налево',
attribute_label_langcode : 'Язык',
general_tab : 'Основной',
attrib_tab : 'Атрибуты',
events_tab : 'События',
fieldset_general_tab : 'Основные Установки',
fieldset_attrib_tab : 'Элемент Атрибуты',
fieldset_events_tab : 'Элемент События',
title_ins_element : 'Элемент Вставка',
title_del_element : 'Элемент События',
title_acronym_element : 'Элемент Акроним',
title_abbr_element : 'Элемент Аббревиатура',
title_cite_element : 'Элемент Цитирование',
remove : 'Убрать',
not_set : '--не установлен--',
insert_date : 'Вставить текущие дату/время'
}}});

tinyMCE.addI18n('ru.xhtmlxtras_dlg',{
    attribute_label_title:"Title",
    attribute_label_id:"ID",
    attribute_label_class:"Class",
    attribute_label_style:"Style",
    attribute_label_cite:"Cite",
    attribute_label_datetime:"Date/Time",
    attribute_label_langdir:"Text Direction",
    attribute_option_ltr:"Left to right",
    attribute_option_rtl:"Right to left",
    attribute_label_langcode:"Language",
    attribute_label_tabindex:"TabIndex",
    attribute_label_accesskey:"AccessKey",
    attribute_events_tab:"Events",
    attribute_attrib_tab:"Attributes",
    general_tab:"General",
    attrib_tab:"Attributes",
    events_tab:"Events",
    fieldset_general_tab:"General Settings",
    fieldset_attrib_tab:"Element Attributes",
    fieldset_events_tab:"Element Events",
    title_ins_element:"Insertion Element",
    title_del_element:"Deletion Element",
    title_acronym_element:"Acronym Element",
    title_abbr_element:"Abbreviation Element",
    title_cite_element:"Citation Element",
    remove:"Remove",
    insert_date:"Insert current date/time",
    option_ltr:"Left to right",
    option_rtl:"Right to left",
    attribs_title:"Insert/Edit Attributes"
});
