// RU lang variables UTF-8
tinyMCE.addI18n({ru: { style : {

title : 'Редактировать CSS Стиль',
styleinfo_desc : 'Редактировать CSS Стиль',
apply : 'Принять',
text_tab : 'Текст',
background_tab : 'Фон',
block_tab : 'Блок',
box_tab : 'Бокс',
border_tab : 'Граница',
list_tab : 'Список',
positioning_tab : 'Позиционирование',
text_props : 'Текст',
text_font : 'Шрифт',
text_size : 'Размер',
text_weight : 'Ширина',
text_style : 'Стиль',
text_variant : 'Вариант',
text_lineheight : 'Высота строки',
text_case : 'Регистр',
text_color : 'Цвет',
text_decoration : 'Оформление',
text_overline : 'Надчеркивание',
text_underline : 'Подчеркивание',
text_striketrough : 'Зачеркивание',
text_blink : 'Мерцание',
text_none : 'Нет',
background_color : 'Цвет фона',
background_image : 'Фоновое изображение',
background_repeat : 'Повторить',
background_attachment : 'Прокрутка фонового изображения',
background_hpos : 'Горизонтальная позиция',
background_vpos : 'Вертикальная позиция',
block_wordspacing : 'Расстояние между словами',
block_letterspacing : 'Расстояние между буквами',
block_vertical_alignment : 'Выравнивание по вертикали',
block_text_align : 'Выравнивание текста',
block_text_indent : 'Отступ первой строки',
block_whitespace : 'Пробелы',
block_display : 'Отображение',
box_width : 'Ширина',
box_height : 'Высота',
box_float : 'Выравнивание с обтеканием',
box_clear : 'Запрет обтекания',
padding : 'Поля',
same : 'Тоже для остальных',
top : 'Верх',
right : 'Право',
bottom : 'Низ',
left : 'Лево',
margin : 'Отступ',
style : 'Стиль',
width : 'Ширина',
height : 'Высота',
color : 'Цвет',
list_type : 'Тип',
bullet_image : 'Маркер абзаца',
position : 'Позиция',
positioning_type : 'Тип',
visibility : 'Видимость',
zindex : 'Наложение',
overflow : 'Переполнение',
placement : 'Размещение',
clip : 'Позиционирование'
}}});


tinyMCE.addI18n('ru.style_dlg',{
    title:"Edit CSS Style",
    apply:"Apply",
    text_tab:"Text",
    background_tab:"Background",
    block_tab:"Block",
    box_tab:"Box",
    border_tab:"Border",
    list_tab:"List",
    positioning_tab:"Positioning",
    text_props:"Text",
    text_font:"Font",
    text_size:"Size",
    text_weight:"Weight",
    text_style:"Style",
    text_variant:"Variant",
    text_lineheight:"Line height",
    text_case:"Case",
    text_color:"Color",
    text_decoration:"Decoration",
    text_overline:"overline",
    text_underline:"underline",
    text_striketrough:"strikethrough",
    text_blink:"blink",
    text_none:"none",
    background_color:"Background color",
    background_image:"Background image",
    background_repeat:"Repeat",
    background_attachment:"Attachment",
    background_hpos:"Horizontal position",
    background_vpos:"Vertical position",
    block_wordspacing:"Word spacing",
    block_letterspacing:"Letter spacing",
    block_vertical_alignment:"Vertical alignment",
    block_text_align:"Text align",
    block_text_indent:"Text indent",
    block_whitespace:"Whitespace",
    block_display:"Display",
    box_width:"Width",
    box_height:"Height",
    box_float:"Float",
    box_clear:"Clear",
    padding:"Padding",
    same:"Same for all",
    top:"Top",
    right:"Right",
    bottom:"Bottom",
    left:"Left",
    margin:"Margin",
    style:"Style",
    width:"Width",
    height:"Height",
    color:"Color",
    list_type:"Type",
    bullet_image:"Bullet image",
    position:"Position",
    positioning_type:"Type",
    visibility:"Visibility",
    zindex:"Z-index",
    overflow:"Overflow",
    placement:"Placement",
    clip:"Clip"
});