// Extasy CMS Dashboard scripts v 4.3// RU lang variables UTF-8

/* Remember to namespace the language parameters lang_<your plugin>_<some name> */

tinyMCE.addI18n({ru: {

template_title : 'Это шаблон для всплывающего окна',
template_desc : 'Это шаблон для кнопки'
}});

// RU lang variables UTF-8

tinyMCE.addI18n({ru: {
    insert_advhr_desc : 'Вставить / редактировать горизонтальный разделитель',
insert_advhr_width : 'Ширина',
insert_advhr_size : 'Высота',
insert_advhr_noshade : 'Без тени'
}});


tinyMCE.addI18n('ru.advhr_dlg',{
    width:"Width",
    size:"Height",
    noshade:"No shadow"
});
// RU lang variables UTF-8
tinyMCE.addI18n({ru: { advimage : {

tab_general : 'Основные',
tab_appearance : 'Визуализация',
tab_advanced : 'Расширенные',
general : 'Главные',
title : 'Заголовок',
preview : 'Предпросмотр',
constrain_proportions : 'Сохранить пропорции',
langdir : 'Описание языка',
langcode : 'Код языка',
long_desc : 'Полное описание',
style : 'Стили',
classes : 'Классы',
ltr : 'Слева направо',
rtl : 'Справа налево',
id : 'Ид',
image_map : 'Карта изображения',
swap_image : 'Подмена картинки',
alt_image : 'Альтернативное изображение',
mouseover : 'при наведении мыши',
mouseout : 'когда уводите мышь',
misc : 'Прочее',
example_img : 'Визуализация&nbsp;расположения&nbsp;картинки',
missing_alt : 'Продолжить без Описания Изображения? Без описания, изображение может быть недоступно для пользователей, использующих текстовые браузеры или отключивших показ изображений.'
}}});
tinyMCE.addI18n({ru: { advimage_dlg : {

    tab_general:"Общее",
    tab_appearance:"Внешний вид",
    tab_advanced:"Дополнительно",
    general:"Общее",
    title:"Заголовок",
    preview:"Предпросмотр",
    constrain_proportions:"Сохранить пропорции",
    langdir:"Language direction",
    langcode:"Language code",
    long_desc:"Long description link",
    style:"Стиль",
    classes:"Классы",
    ltr:"Слева направо",
    rtl:"Справа налево",
    id:"Id",
    map:"Image map",
    swap_image:"Swap image",
    alt_image:"Alternative image",
    mouseover:"for mouse over",
    mouseout:"for mouse out",
    misc:"Прочее",
    example_img:"Appearance preview image",
    missing_alt:"Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.",
    dialog_title:"Insert/edit image",
    src:"Image URL",
    alt:"Image description",
    list:"Image list",
    border:"Border",
    dimensions:"Dimensions",
    vspace:"Vertical space",
    hspace:"Horizontal space",
    align:"Alignment",
    align_baseline:"Baseline",
    align_top:"Top",
    align_middle:"Middle",
    align_bottom:"Bottom",
    align_texttop:"Text top",
    align_textbottom:"Text bottom",
    align_left:"Left",
    align_right:"Right",
    image_list:"Image list"
}}});
// RU lang variables UTF-8
tinyMCE.addI18n({ru: { advlink : {

general_tab : 'Основные',
popup_tab : 'Всплывающие',
events_tab : 'События',
advanced_tab : 'Расширенные',
general_props : 'Основные свойства',
popup_props : 'Свойства всплывющих элементов',
event_props : 'События',
advanced_props : 'Расширенные настройки',
popup_opts : 'Опции',
anchor_names : 'Якоря',
target_same : 'Открывать в этом окне / фрейме',
target_parent : 'Открывать в родительском окне / фрейме',
target_top : 'Открывать в верхнем фрейме (заменять все фреймы)',
target_blank : 'Открывать в новом окне',
popup : 'Всплывающее окно Javascript',
popup_url : 'Всплывающий URL',
popup_name : 'Имя окна',
popup_return : 'Вставить \'return false\'',
popup_scrollbars : 'Показывать линейки прокрутки',
popup_statusbar : 'Показывать строку состояния',
popup_toolbar : 'Показывать панели инструментов',
popup_menubar : 'Показывать панель меню',
popup_location : 'Показывать панель расположения',
popup_resizable : 'Позволить изменять размеры окна',
popup_dependent : 'Зависимость (только Mozilla/Firefox)',
popup_size : 'Размер',
popup_position : 'Расположение (X/Y)',
id : 'Id',
style: 'Стиль',
classes : 'Классы',
target_name : 'Имя цели',
langdir : 'Направление письма в языке',
target_langcode : 'Целевой язык',
langcode : 'Код языка',
encoding : 'Целевая кодировка',
mime : 'Целевой MIME тип',
rel : 'Зависимость страница -> цель',
rev : 'Зависимость цель -> страница',
tabindex : 'Индекс таблицы',
accesskey : 'Ключ доступа',
ltr : 'Слева направо',
rtl : 'Справа налево'
}}});
tinyMCE.addI18n( {ru : { advlink_dlg : {
    title:"Insert/edit link",
    url:"Link URL",
    target:"Target",
    titlefield:"Title",
    is_email:"The URL you entered seems to be an email address, do you want to add the required mailto: prefix?",
    is_external:"The URL you entered seems to external link, do you want to add the required http:// prefix?",
    list:"Link list",
    general_tab:"General",
    popup_tab:"Popup",
    events_tab:"Events",
    advanced_tab:"Advanced",
    general_props:"General properties",
    popup_props:"Popup properties",
    event_props:"Events",
    advanced_props:"Advanced properties",
    popup_opts:"Options",
    anchor_names:"Anchors",
    target_same:"Open in this window / frame",
    target_parent:"Open in parent window / frame",
    target_top:"Open in top frame (replaces all frames)",
    target_blank:"Open in new window",
    popup:"Javascript popup",
    popup_url:"Popup URL",
    popup_name:"Window name",
    popup_return:"Insert 'return false'",
    popup_scrollbars:"Show scrollbars",
    popup_statusbar:"Show status bar",
    popup_toolbar:"Show toolbars",
    popup_menubar:"Show menu bar",
    popup_location:"Show location bar",
    popup_resizable:"Make window resizable",
    popup_dependent:"Dependent (Mozilla/Firefox only)",
    popup_size:"Size",
    popup_position:"Position (X/Y)",
    id:"Id",
    style:"Style",
    classes:"Classes",
    target_name:"Target name",
    langdir:"Language direction",
    target_langcode:"Target language",
    langcode:"Language code",
    encoding:"Target character encoding",
    mime:"Target MIME type",
    rel:"Relationship page to target",
    rev:"Relationship target to page",
    tabindex:"Tabindex",
    accesskey:"Accesskey",
    ltr:"Left to right",
    rtl:"Right to left",
    link_list:"Link list"
}}});

// RU lang variables UTF-8

tinyMCE.addI18n({ru: {
autosave_unload_msg : 'Изменения не будут потеряны если Вы уйдёте с этой страницы.'
}});

// RU lang variables UTF-8

tinyMCE.addI18n({ru: {
directionality_ltr_desc : 'Направление слева направо',
directionality_rtl_desc : 'Направление справа налево'
}});

// RU lang variables UTF-8
tinyMCE.addI18n({ru: { emotions : {

title : 'Вставить смайлик',
desc : 'Смайлики',
cool : 'Круто',
cry : 'Плач',
embarassed : 'Смущенный',
foot_in_mouth : 'Косноязычный',
frown : 'Нахмуреный',
innocent : 'Святой',
kiss : 'Поцелуй',
laughing : 'Смех',
money_mouth : 'Дельный',
sealed : 'Заклеенный',
smile : 'Улыбка',
surprised : 'Сюрприз',
tongue_out : 'Высунутый язык',
undecided : 'Нерешительный',
wink : 'Подмигнуть',
yell : 'Вопль'
}}});


tinyMCE.addI18n('ru.emotions_dlg',{
    title:"Insert emotion",
    desc:"Emotions",
    cool:"Cool",
    cry:"Cry",
    embarassed:"Embarassed",
    foot_in_mouth:"Foot in mouth",
    frown:"Frown",
    innocent:"Innocent",
    kiss:"Kiss",
    laughing:"Laughing",
    money_mouth:"Money mouth",
    sealed:"Sealed",
    smile:"Smile",
    surprised:"Surprised",
    tongue_out:"Tongue out",
    undecided:"Undecided",
    wink:"Wink",
    yell:"Yell"
});
// RU lang variables UTF-8
tinyMCE.addI18n({ru: { flash : {

title : 'Вставить / Редактировать флеш-ролик',
desc : 'Вставить / Редактировать флеш-ролик',
file : 'Флеш-Файл (.swf)',
size : 'Размер',
list : 'Флеш-файлы',
props : 'Свойства флеш',
general : 'Основное'
}}});

// RU lang variables UTF-8
tinyMCE.addI18n({ru: { fullpage : {

	title : 'Свойства документа',
	desc : 'Свойства документа',
	meta_tab : 'Основные',
	appearance_tab : 'Видимость',
	advanced_tab : 'Дополнительные',
	meta_props : 'Мета информация',
	langprops : 'Язык и кодировка',
	meta_title : 'Название',
	meta_keywords : 'Ключевые слова',
	meta_description : 'Описание',
	meta_robots : 'Роботы',
	doctypes : 'Тип документа (Doctype)',
	langcode : 'Код языка',
	langdir : 'Направление языка',
	ltr : 'Слева направо',
	rtl : 'Справа налево',
	xml_pi : 'XML декларация',
	encoding : 'Кодировка',
	appearance_bgprops : 'Свойства фона',
	appearance_marginprops : 'Отступы',
	appearance_linkprops : 'Цвет ссылок',
	appearance_textprops : 'Свойства текста',
	bgcolor : 'Цвет фона',
	bgimage : 'Фоновое изображение',
	left_margin : 'Отступ слева',
	right_margin : 'Отступ справа',
	top_margin : 'Отступ сверху',
	bottom_margin : 'Отступ снизу',
	text_color : 'Цвет текста',
	font_size : 'Размер шрифта',
	font_face : 'Шрифт',
	link_color : 'Цвет ссылки',
	hover_color : 'Цвет при наведении на ссылку',
	visited_color : 'Цвет посещенной ссылки',
	active_color : 'Цвет активной ссылки',
	textcolor : 'Цвет',
	fontsize : 'Размер шрифта',
	fontface : 'Тип шрифта',
	meta_index_follow : 'Индексировать и следовать по ссылкам',
	meta_index_nofollow : 'Индексировать и не следовать по ссылкам',
	meta_noindex_follow : 'Не индексировать, но следовать по ссылкам',
	meta_noindex_nofollow : 'Не индексировать и не следовать по ссылкам',
	appearance_style : 'Таблица стилей и свойства стиля',
	stylesheet : 'Таблица стилей',
	style : 'Стиль',
	author : 'Автор',
	copyright : 'Авторское право',
	add : 'Добавить новый элемент',
	remove : 'Удалить выделенный элемент',
	moveup : 'Переместить выбранный элемент вверх',
	movedown : 'Переместить выделенный элемент вниз',
	head_elements : 'Элемент главный',
	info : 'Информация',
	info_text : '',
	add_title : 'Элемент название',
	add_meta : 'Элемент мета',
	add_script : 'Элемент скрипт',
	add_style : 'Элемент стиль',
	add_link : 'Элемент ссылка',
	add_base : 'Элемент базовый',
	add_comment : 'Элемент комментарий',
	title_element : 'Элемент название',
	script_element : 'Элемент скрипт',
	style_element : 'Элемент стиль',
	base_element : 'Элемент базовый',
	link_element : 'Элемент ссылка',
	meta_element : 'Элемент мета',
	comment_element : 'Комментарий',
	src : 'Источник',
	language : 'Язык',
	href : 'Href',
	target : 'Цель',
	rel : 'Вып',
	type : 'Тип',
	charset : 'Кодировка',
	defer : 'Задержка',
	media : 'Медиа',
	properties : 'Свойства',
	name : 'Имя',
	value : 'Значение',
	content : 'Контент',
	rel : 'Вып',
	rev : 'Обр',
	hreflang : 'Href язык',
	general_props : 'Основные',
	advanced_props : 'Дополнительные',
	delta_width : 0,
	delta_height : 0
}}});


tinyMCE.addI18n('ru.fullpage_dlg',{
    title:"Document properties",
    meta_tab:"General",
    appearance_tab:"Appearance",
    advanced_tab:"Advanced",
    meta_props:"Meta information",
    langprops:"Language and encoding",
    meta_title:"Title",
    meta_keywords:"Keywords",
    meta_description:"Description",
    meta_robots:"Robots",
    doctypes:"Doctype",
    langcode:"Language code",
    langdir:"Language direction",
    ltr:"Left to right",
    rtl:"Right to left",
    xml_pi:"XML declaration",
    encoding:"Character encoding",
    appearance_bgprops:"Background properties",
    appearance_marginprops:"Body margins",
    appearance_linkprops:"Link colors",
    appearance_textprops:"Text properties",
    bgcolor:"Background color",
    bgimage:"Background image",
    left_margin:"Left margin",
    right_margin:"Right margin",
    top_margin:"Top margin",
    bottom_margin:"Bottom margin",
    text_color:"Text color",
    font_size:"Font size",
    font_face:"Font face",
    link_color:"Link color",
    hover_color:"Hover color",
    visited_color:"Visited color",
    active_color:"Active color",
    textcolor:"Color",
    fontsize:"Font size",
    fontface:"Font family",
    meta_index_follow:"Index and follow the links",
    meta_index_nofollow:"Index and don't follow the links",
    meta_noindex_follow:"Do not index but follow the links",
    meta_noindex_nofollow:"Do not index and don\'t follow the links",
    appearance_style:"Stylesheet and style properties",
    stylesheet:"Stylesheet",
    style:"Style",
    author:"Author",
    copyright:"Copyright",
    add:"Add new element",
    remove:"Remove selected element",
    moveup:"Move selected element up",
    movedown:"Move selected element down",
    head_elements:"Head elements",
    info:"Information",
    add_title:"Title element",
    add_meta:"Meta element",
    add_script:"Script element",
    add_style:"Style element",
    add_link:"Link element",
    add_base:"Base element",
    add_comment:"Comment node",
    title_element:"Title element",
    script_element:"Script element",
    style_element:"Style element",
    base_element:"Base element",
    link_element:"Link element",
    meta_element:"Meta element",
    comment_element:"Comment",
    src:"Src",
    language:"Language",
    href:"Href",
    target:"Target",
    type:"Type",
    charset:"Charset",
    defer:"Defer",
    media:"Media",
    properties:"Properties",
    name:"Name",
    value:"Value",
    content:"Content",
    rel:"Rel",
    rev:"Rev",
    hreflang:"Href lang",
    general_props:"General",
    advanced_props:"Advanced"
});
// RU lang variables UTF-8
tinyMCE.addI18n({ru: {

fullscreen_title : 'Полноэкранный режим',
fullscreen_desc : 'Включить полноэкранный режим'
}});

// RU lang variables UTF-8
tinyMCE.addI18n({ru: {
iespell_desc : 'Запустить проверку орфографии',
iespell_download : "ieSpell не обнаружен. нажмите OK, чтобы перейти на страницу загрузки."
}});


// RU lang variables UTF-8
tinyMCE.addI18n({ru: {

insertdate_def_fmt : '%d %m %Y',
inserttime_def_fmt : '%H:%M:%S',
insertdate_desc : 'Вставить дату',
inserttime_desc : 'Вставить время',
inserttime_months_long : new Array("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря"),
inserttime_months_short : new Array("янв", "фев", "март", "апр", "май", "июнь", "июль", "авг", "сент", "окт", "нбр", "дек"),
inserttime_day_long : new Array("воскресенье", "понедельник", "вторник", "среда", "четверг", "пятница", "суббота", "воскресенье"),
inserttime_day_short : new Array("вск", "пн", "вт", "ср", "чтв", "птн", "сб", "вск")
}});

// RU lang variables UTF-8
tinyMCE.addI18n({ru: { layer : {

insertlayer_desc : 'Вставить новый слой',
forward_desc : 'Переместить вперед',
backward_desc : 'Переместить назад',
absolute_desc : 'Вкл / Выкл абсолютное позиционирование',
content : 'Новый слой...'
}}});

// RU lang variables UTF-8
tinyMCE.addI18n({ru: { media: {
    title : 'Вставить / редактировать медиа',
    desc : 'Вставить / редактировать медиа',
    general : 'Основной',
    advanced : 'Дополнительный',
    file : 'Файл',
    list : 'Список',
    size : 'Размеры',
    preview : 'Предпросмотр',
    constrain_proportions : 'Поддерживать пропорции',
    type : 'Тип',
    id : 'Ид',
    name : 'Имя',
    class_name : 'Класс',
    vspace : 'V-Отступ',
    hspace : 'H-Отступ',
    play : 'Авто проигрывание',
    loop : 'Цикл',
    menu : 'Показать меню',
    quality : 'Качество',
    scale : 'Масштаб',
    align : 'Выравнивание',
    salign : 'S-Выравнивание',
    wmode : 'W-Режим',
    bgcolor : 'Фон',
    base : 'База',
    flashvars : 'Переменные флеш',
    liveconnect : 'SWLiveConnect',
    autohref : 'Авто Ссылка',
    cache : 'Кеш',
    hidden : 'Скрытый',
    controller : 'Контроллер',
    kioskmode : 'Режим Kiosk',
    playeveryframe : 'Проигрывать каждый кадр',
    targetcache : 'Целевой кеш',
    correction : 'No correction',
    enablejavascript : 'Включить JavaScript',
    starttime : 'Время начала',
    endtime : 'Время окончания',
    href : 'Ссылка',
    qtsrcchokespeed : 'Уменьшить скорость',
    target : 'Цель',
    volume : 'Громкость',
    autostart : 'Авто запуск',
    enabled : 'Включено',
    fullscreen : 'Полный экран',
    invokeurls : 'Активизировать ссылки',
    mute : 'Тишина',
    stretchtofit : 'Растянуть до вхождения',
    windowlessvideo : 'Безоконное видео',
    balance : 'Баланс',
    baseurl : 'Базовая ссылка',
    captioningid : 'Ид ввода субтитров',
    currentmarker : 'Текущая отметка',
    currentposition : 'Текущая позиция',
    defaultframe : 'Кадр по умолчанию',
    playcount : 'Счетчик',
    rate : 'Частота',
    uimode : 'UI режим',
    flash_options : 'Опции Флеш',
    qt_options : 'Опции Quicktime',
    wmp_options : 'Опции проигрывателя Windows media',
    rmp_options : 'Опции проигрывателя Real media',
    shockwave_options : 'Опции Shockwave',
    autogotourl : 'Авто переход по ссылке',
    center : 'Центр',
    imagestatus : 'Статус изображения',
    maintainaspect : 'Поддерживать аспект',
    nojava : 'Без java',
    prefetch : 'Упреждение',
    shuffle : 'Перемешать',
    console : 'Консоль',
    numloop : 'Количество циклов',
    controls : 'Управления',
    scriptcallbacks : 'Обратный вызов скрипта',
    swstretchstyle : 'Стиль растяжения',
    swstretchhalign : 'H-Выравнивание растяжения',
    swstretchvalign : 'V-Выравнивание растяжения',
    sound : 'Звук',
    progress : 'Прогресс',
    qtsrc : 'QT Исх',
    qt_stream_warn : 'Потоковые rtsp ресурсы должны быть добавлены в поле QT Исх в дополнительную графу.\nВы также должны добавить не потоковую версию в поле Исх..'
}}});


tinyMCE.addI18n('ru.media_dlg',{
    title:"Insert / edit embedded media",
    general:"General",
    advanced:"Advanced",
    file:"File/URL",
    list:"List",
    size:"Dimensions",
    preview:"Preview",
    constrain_proportions:"Constrain proportions",
    type:"Type",
    id:"Id",
    name:"Name",
    class_name:"Class",
    vspace:"V-Space",
    hspace:"H-Space",
    play:"Auto play",
    loop:"Loop",
    menu:"Show menu",
    quality:"Quality",
    scale:"Scale",
    align:"Align",
    salign:"SAlign",
    wmode:"WMode",
    bgcolor:"Background",
    base:"Base",
    flashvars:"Flashvars",
    liveconnect:"SWLiveConnect",
    autohref:"AutoHREF",
    cache:"Cache",
    hidden:"Hidden",
    controller:"Controller",
    kioskmode:"Kiosk mode",
    playeveryframe:"Play every frame",
    targetcache:"Target cache",
    correction:"No correction",
    enablejavascript:"Enable JavaScript",
    starttime:"Start time",
    endtime:"End time",
    href:"Href",
    qtsrcchokespeed:"Choke speed",
    target:"Target",
    volume:"Volume",
    autostart:"Auto start",
    enabled:"Enabled",
    fullscreen:"Fullscreen",
    invokeurls:"Invoke URLs",
    mute:"Mute",
    stretchtofit:"Stretch to fit",
    windowlessvideo:"Windowless video",
    balance:"Balance",
    baseurl:"Base URL",
    captioningid:"Captioning id",
    currentmarker:"Current marker",
    currentposition:"Current position",
    defaultframe:"Default frame",
    playcount:"Play count",
    rate:"Rate",
    uimode:"UI Mode",
    flash_options:"Flash options",
    qt_options:"Quicktime options",
    wmp_options:"Windows media player options",
    rmp_options:"Real media player options",
    shockwave_options:"Shockwave options",
    autogotourl:"Auto goto URL",
    center:"Center",
    imagestatus:"Image status",
    maintainaspect:"Maintain aspect",
    nojava:"No java",
    prefetch:"Prefetch",
    shuffle:"Shuffle",
    console:"Console",
    numloop:"Num loops",
    controls:"Controls",
    scriptcallbacks:"Script callbacks",
    swstretchstyle:"Stretch style",
    swstretchhalign:"Stretch H-Align",
    swstretchvalign:"Stretch V-Align",
    sound:"Sound",
    progress:"Progress",
    qtsrc:"QT Src",
    qt_stream_warn:"Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..",
    align_top:"Top",
    align_right:"Right",
    align_bottom:"Bottom",
    align_left:"Left",
    align_center:"Center",
    align_top_left:"Top left",
    align_top_right:"Top right",
    align_bottom_left:"Bottom left",
    align_bottom_right:"Bottom right",
    flv_options:"Flash video options",
    flv_scalemode:"Scale mode",
    flv_buffer:"Buffer",
    flv_startimage:"Start image",
    flv_starttime:"Start time",
    flv_defaultvolume:"Default volumne",
    flv_hiddengui:"Hidden GUI",
    flv_autostart:"Auto start",
    flv_loop:"Loop",
    flv_showscalemodes:"Show scale modes",
    flv_smoothvideo:"Smooth video",
    flv_jscallback:"JS Callback"
});
// RU lang variables UTF-8
tinyMCE.addI18n({ru: {

paste_text_desc : 'Вставить как простой текст',
paste_text_title : 'Используйте CTRL+V для вставки текста в окошко.',
paste_text_linebreaks : 'Сохранить переносы строк',
paste_word_desc : 'Вставить из Word',
paste_word_title : 'Используйте CTRL+V для вставки текста в окошко.',
selectall_desc : 'Выделить всё'
}});


tinyMCE.addI18n('ru.paste_dlg',{
    text_title:"Use CTRL+V on your keyboard to paste the text into the window.",
    text_linebreaks:"Keep linebreaks",
    word_title:"Use CTRL+V on your keyboard to paste the text into the window."
});
// RU lang variables UTF-8
tinyMCE.addI18n({ru: {
preview_desc : 'Предварительный просмотр'
}});

// RU lang variables UTF-8
tinyMCE.addI18n({ru: {
print_desc : 'Распечатать'
}});

// RU lang variables UTF-8
tinyMCE.addI18n({ru: {

save_desc : 'Сохранить'
}});

// RU lang variables UTF-8
tinyMCE.addI18n({ru: {

searchreplace_search_desc : 'Найти',
searchreplace_searchnext_desc : 'Найти опять',
searchreplace_replace_desc : 'Найти / Заменить',
searchreplace_notfound : 'Поиск завершён. Искомое выражение не найдено.',
searchreplace_search_title : 'Найти',
searchreplace_replace_title : 'Найти / Заменить',
searchreplace_allreplaced : 'Замена была выполнена во всех случаях совпадения искомого выражения.',
searchreplace_findwhat : 'Найти что',
searchreplace_replacewith : 'Заменить чем',
searchreplace_direction : 'Направление',
searchreplace_up : 'Вверх',
searchreplace_down : 'Вниз',
searchreplace_case : 'С учётом регистра',
searchreplace_findnext : 'Найти&nbsp;следующее',
searchreplace_replace : 'Заменить',
searchreplace_replaceall : 'Заменить&nbsp;везде',
searchreplace_cancel : 'Отменить'
}});


tinyMCE.addI18n('ru.searchreplace_dlg',{
    searchnext_desc:"Find again",
    notfound:"The search has been completed. The search string could not be found.",
    search_title:"Find",
    replace_title:"Find/Replace",
    allreplaced:"All occurrences of the search string were replaced.",
    findwhat:"Find what",
    replacewith:"Replace with",
    direction:"Direction",
    up:"Up",
    down:"Down",
    mcase:"Match case",
    findnext:"Find next",
    replace:"Replace",
    replaceall:"Replace all"
});
// RU lang variables UTF-8
tinyMCE.addI18n({ru: { spellchecker : {

	desc : 'Вкл / Выкл проверку правописания',
	menu : 'Свойства проверки правописания',
	ignore_word : 'Игнорировать слово',
	ignore_words : 'Игнорировать все',
	langs : 'Языки',
	wait : 'Пожалуйста подождите...',
	swait : 'Проверка правописания, пожалуйста подождите...',
	sug : 'Варианты',
	no_sug : 'Нет вариантов',
	no_mpell : 'Ошибок не найдено.'
}}});

// RU lang variables UTF-8
tinyMCE.addI18n({ru: { style : {

title : 'Редактировать CSS Стиль',
styleinfo_desc : 'Редактировать CSS Стиль',
apply : 'Принять',
text_tab : 'Текст',
background_tab : 'Фон',
block_tab : 'Блок',
box_tab : 'Бокс',
border_tab : 'Граница',
list_tab : 'Список',
positioning_tab : 'Позиционирование',
text_props : 'Текст',
text_font : 'Шрифт',
text_size : 'Размер',
text_weight : 'Ширина',
text_style : 'Стиль',
text_variant : 'Вариант',
text_lineheight : 'Высота строки',
text_case : 'Регистр',
text_color : 'Цвет',
text_decoration : 'Оформление',
text_overline : 'Надчеркивание',
text_underline : 'Подчеркивание',
text_striketrough : 'Зачеркивание',
text_blink : 'Мерцание',
text_none : 'Нет',
background_color : 'Цвет фона',
background_image : 'Фоновое изображение',
background_repeat : 'Повторить',
background_attachment : 'Прокрутка фонового изображения',
background_hpos : 'Горизонтальная позиция',
background_vpos : 'Вертикальная позиция',
block_wordspacing : 'Расстояние между словами',
block_letterspacing : 'Расстояние между буквами',
block_vertical_alignment : 'Выравнивание по вертикали',
block_text_align : 'Выравнивание текста',
block_text_indent : 'Отступ первой строки',
block_whitespace : 'Пробелы',
block_display : 'Отображение',
box_width : 'Ширина',
box_height : 'Высота',
box_float : 'Выравнивание с обтеканием',
box_clear : 'Запрет обтекания',
padding : 'Поля',
same : 'Тоже для остальных',
top : 'Верх',
right : 'Право',
bottom : 'Низ',
left : 'Лево',
margin : 'Отступ',
style : 'Стиль',
width : 'Ширина',
height : 'Высота',
color : 'Цвет',
list_type : 'Тип',
bullet_image : 'Маркер абзаца',
position : 'Позиция',
positioning_type : 'Тип',
visibility : 'Видимость',
zindex : 'Наложение',
overflow : 'Переполнение',
placement : 'Размещение',
clip : 'Позиционирование'
}}});


tinyMCE.addI18n('ru.style_dlg',{
    title:"Edit CSS Style",
    apply:"Apply",
    text_tab:"Text",
    background_tab:"Background",
    block_tab:"Block",
    box_tab:"Box",
    border_tab:"Border",
    list_tab:"List",
    positioning_tab:"Positioning",
    text_props:"Text",
    text_font:"Font",
    text_size:"Size",
    text_weight:"Weight",
    text_style:"Style",
    text_variant:"Variant",
    text_lineheight:"Line height",
    text_case:"Case",
    text_color:"Color",
    text_decoration:"Decoration",
    text_overline:"overline",
    text_underline:"underline",
    text_striketrough:"strikethrough",
    text_blink:"blink",
    text_none:"none",
    background_color:"Background color",
    background_image:"Background image",
    background_repeat:"Repeat",
    background_attachment:"Attachment",
    background_hpos:"Horizontal position",
    background_vpos:"Vertical position",
    block_wordspacing:"Word spacing",
    block_letterspacing:"Letter spacing",
    block_vertical_alignment:"Vertical alignment",
    block_text_align:"Text align",
    block_text_indent:"Text indent",
    block_whitespace:"Whitespace",
    block_display:"Display",
    box_width:"Width",
    box_height:"Height",
    box_float:"Float",
    box_clear:"Clear",
    padding:"Padding",
    same:"Same for all",
    top:"Top",
    right:"Right",
    bottom:"Bottom",
    left:"Left",
    margin:"Margin",
    style:"Style",
    width:"Width",
    height:"Height",
    color:"Color",
    list_type:"Type",
    bullet_image:"Bullet image",
    position:"Position",
    positioning_type:"Type",
    visibility:"Visibility",
    zindex:"Z-index",
    overflow:"Overflow",
    placement:"Placement",
    clip:"Clip"
});
// RU lang variables UTF-8
tinyMCE.addI18n({ru: { table : {
general_tab : 'Основные',
advanced_tab : 'Расширенные',
general_props : 'Основные свойства',
advanced_props : 'Расширенные свойства',
desc : 'Вставить новую таблицу',
row_before_desc : 'Вставить строку перед',
row_after_desc : 'Вставить строку после',
delete_row_desc : 'Удалить строку',
col_before_desc : 'Вставить колонку перед',
col_after_desc : 'Вставить колонку после',
delete_col_desc : 'Удалить колонку',
rowtype : 'Строка в части таблицы',
title : 'Вставить/Изменить таблицу',
width : 'Ширина',
height : 'Высота',
cols : 'Колонки',
rows : 'Строки',
cellspacing : 'Расстояние между ячейками',
cellpadding : 'Отступ в ячейках',
border : 'Граница',
align : 'Выравнивание',
align_default : 'По-умолчанию',
align_left : 'Всево',
align_right : 'Вправо',
align_middle : 'По центру',
row_title : 'Свойства строки таблицы',
cell_title : 'Свойства ячейки таблицы',
cell_type : 'Тип ячейки',
row_desc : 'Свойства строки таблицы',
cell_desc : 'Свойства ячейки таблицы',
valign : 'Вертикальное выравнивание',
align_top : 'По верху',
align_bottom : 'По низу',
props_desc : 'Свойства таблицы',
bordercolor : 'Цвет рамки',
bgcolor : 'Цвет фона',
merge_cells_title : 'Объединить ячейки таблицы',
split_cells_desc : 'Разделить ячейки таблицы',
merge_cells_desc : 'Объединить ячейки таблицы',
cut_row_desc : 'Вылезать строку таблицы',
copy_row_desc : 'Скопировать строку таблицы',
paste_row_before_desc : 'Вставить строку таблицы перед',
paste_row_after_desc : 'Вставить строку таблицы после',
id : 'Ид',
style: 'Стиль',
langdir : 'Описание языка',
langcode : 'Код языка',
mime : 'Целевой MIME тип',
ltr : 'Слева направо',
rtl : 'Справа налево',
bgimage : 'Фоновое изображение',
summary : 'Краткое описание',
td : "Тело",
th : "Заголовок",
cell_cell : 'Обновить текущую ячейку',
cell_row : 'Обновить текущую строку',
cell_all : 'Обновить все ячейки в таблице',
row_row : 'Обновить текущую строку',
row_odd : 'Обновить нечетные строки в таблице',
row_even : 'Обновить четные строки в таблице',
row_all : 'Обновить все строки в таблице',
thead : 'Заголовок таблицы',
tbody : 'Тело таблицы',
tfoot : 'Футер таблицы',
del : 'Удалить таблицу',
scope : 'Границы',
row : 'Строка',
col : 'Колонка',
rowgroup : 'Группа строк',
colgroup : 'Группа колонок',
col_limit : 'Вы превысили максимально допустимое количество колонок - {$cols}.',
row_limit : 'Вы превысили максимально допустимое количество строк - {$rows}.',
cell_limit : 'Вы превысили максимально допустимое количество ячеек -  {$cells}.',
missing_scope: 'Вы уверены, что хотите продолжать не обозначив границы ячеек шапки таблицы? Без этого, возможно, некоторым пользователям будет затруднительно понять, что за данные находятся в таблице.'
}}});


tinyMCE.addI18n('ru.table_dlg',{
    general_tab:"General",
    advanced_tab:"Advanced",
    general_props:"General properties",
    advanced_props:"Advanced properties",
    rowtype:"Row in table part",
    title:"Insert/Modify table",
    width:"Width",
    height:"Height",
    cols:"Cols",
    rows:"Rows",
    cellspacing:"Cellspacing",
    cellpadding:"Cellpadding",
    border:"Border",
    align:"Alignment",
    align_default:"Default",
    align_left:"Left",
    align_right:"Right",
    align_middle:"Center",
    row_title:"Table row properties",
    cell_title:"Table cell properties",
    cell_type:"Cell type",
    valign:"Vertical alignment",
    align_top:"Top",
    align_bottom:"Bottom",
    bordercolor:"Border color",
    bgcolor:"Background color",
    merge_cells_title:"Merge table cells",
    id:"Id",
    style:"Style",
    langdir:"Language direction",
    langcode:"Language code",
    mime:"Target MIME type",
    ltr:"Left to right",
    rtl:"Right to left",
    bgimage:"Background image",
    summary:"Summary",
    td:"Data",
    th:"Header",
    cell_cell:"Update current cell",
    cell_row:"Update all cells in row",
    cell_all:"Update all cells in table",
    row_row:"Update current row",
    row_odd:"Update odd rows in table",
    row_even:"Update even rows in table",
    row_all:"Update all rows in table",
    thead:"Table Head",
    tbody:"Table Body",
    tfoot:"Table Foot",
    scope:"Scope",
    rowgroup:"Row Group",
    colgroup:"Col Group",
    col_limit:"You've exceeded the maximum number of columns of {$cols}.",
    row_limit:"You've exceeded the maximum number of rows of {$rows}.",
    cell_limit:"You've exceeded the maximum number of cells of {$cells}.",
    missing_scope:"Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.",
    caption:"Table caption",
    frame:"Frame",
    frame_none:"none",
    frame_groups:"groups",
    frame_rows:"rows",
    frame_cols:"cols",
    frame_all:"all",
    rules:"Rules",
    rules_void:"void",
    rules_above:"above",
    rules_below:"below",
    rules_hsides:"hsides",
    rules_lhs:"lhs",
    rules_rhs:"rhs",
    rules_vsides:"vsides",
    rules_box:"box",
    rules_border:"border"
});

// RU lang variables UTF-8
tinyMCE.addI18n({ru: { xhtmlxtras : {
cite_desc : 'Цитирование',
abbr_desc : 'Аббревиатура',
acronym_desc : 'Акроним',
del_desc : 'Стирание',
ins_desc : 'Вставка',
attribute_label_title : 'Заголовок',
attribute_label_id : 'ИД',
attribute_label_class : 'Класс',
attribute_label_style : 'Стиль',
attribute_label_cite : 'Цитировать',
attribute_label_datetime : 'Дата/Время',
attribute_label_langdir : 'Направление Текста',
attribute_option_ltr : 'Слева направо',
attribute_option_rtl : 'Справа налево',
attribute_label_langcode : 'Язык',
general_tab : 'Основной',
attrib_tab : 'Атрибуты',
events_tab : 'События',
fieldset_general_tab : 'Основные Установки',
fieldset_attrib_tab : 'Элемент Атрибуты',
fieldset_events_tab : 'Элемент События',
title_ins_element : 'Элемент Вставка',
title_del_element : 'Элемент События',
title_acronym_element : 'Элемент Акроним',
title_abbr_element : 'Элемент Аббревиатура',
title_cite_element : 'Элемент Цитирование',
remove : 'Убрать',
not_set : '--не установлен--',
insert_date : 'Вставить текущие дату/время'
}}});

tinyMCE.addI18n('ru.xhtmlxtras_dlg',{
    attribute_label_title:"Title",
    attribute_label_id:"ID",
    attribute_label_class:"Class",
    attribute_label_style:"Style",
    attribute_label_cite:"Cite",
    attribute_label_datetime:"Date/Time",
    attribute_label_langdir:"Text Direction",
    attribute_option_ltr:"Left to right",
    attribute_option_rtl:"Right to left",
    attribute_label_langcode:"Language",
    attribute_label_tabindex:"TabIndex",
    attribute_label_accesskey:"AccessKey",
    attribute_events_tab:"Events",
    attribute_attrib_tab:"Attributes",
    general_tab:"General",
    attrib_tab:"Attributes",
    events_tab:"Events",
    fieldset_general_tab:"General Settings",
    fieldset_attrib_tab:"Element Attributes",
    fieldset_events_tab:"Element Events",
    title_ins_element:"Insertion Element",
    title_del_element:"Deletion Element",
    title_acronym_element:"Acronym Element",
    title_abbr_element:"Abbreviation Element",
    title_cite_element:"Citation Element",
    remove:"Remove",
    insert_date:"Insert current date/time",
    option_ltr:"Left to right",
    option_rtl:"Right to left",
    attribs_title:"Insert/Edit Attributes"
});
