// RU lang variables UTF-8
tinyMCE.addI18n({ru: { advimage : {

tab_general : 'Основные',
tab_appearance : 'Визуализация',
tab_advanced : 'Расширенные',
general : 'Главные',
title : 'Заголовок',
preview : 'Предпросмотр',
constrain_proportions : 'Сохранить пропорции',
langdir : 'Описание языка',
langcode : 'Код языка',
long_desc : 'Полное описание',
style : 'Стили',
classes : 'Классы',
ltr : 'Слева направо',
rtl : 'Справа налево',
id : 'Ид',
image_map : 'Карта изображения',
swap_image : 'Подмена картинки',
alt_image : 'Альтернативное изображение',
mouseover : 'при наведении мыши',
mouseout : 'когда уводите мышь',
misc : 'Прочее',
example_img : 'Визуализация&nbsp;расположения&nbsp;картинки',
missing_alt : 'Продолжить без Описания Изображения? Без описания, изображение может быть недоступно для пользователей, использующих текстовые браузеры или отключивших показ изображений.'
}}});
tinyMCE.addI18n({ru: { advimage_dlg : {

    tab_general:"Общее",
    tab_appearance:"Внешний вид",
    tab_advanced:"Дополнительно",
    general:"Общее",
    title:"Заголовок",
    preview:"Предпросмотр",
    constrain_proportions:"Сохранить пропорции",
    langdir:"Language direction",
    langcode:"Language code",
    long_desc:"Long description link",
    style:"Стиль",
    classes:"Классы",
    ltr:"Слева направо",
    rtl:"Справа налево",
    id:"Id",
    map:"Image map",
    swap_image:"Swap image",
    alt_image:"Alternative image",
    mouseover:"for mouse over",
    mouseout:"for mouse out",
    misc:"Прочее",
    example_img:"Appearance preview image",
    missing_alt:"Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.",
    dialog_title:"Insert/edit image",
    src:"Image URL",
    alt:"Image description",
    list:"Image list",
    border:"Border",
    dimensions:"Dimensions",
    vspace:"Vertical space",
    hspace:"Horizontal space",
    align:"Alignment",
    align_baseline:"Baseline",
    align_top:"Top",
    align_middle:"Middle",
    align_bottom:"Bottom",
    align_texttop:"Text top",
    align_textbottom:"Text bottom",
    align_left:"Left",
    align_right:"Right",
    image_list:"Image list"
}}});