// RU lang variables UTF-8
tinyMCE.addI18n({ru: { advlink : {

general_tab : 'Основные',
popup_tab : 'Всплывающие',
events_tab : 'События',
advanced_tab : 'Расширенные',
general_props : 'Основные свойства',
popup_props : 'Свойства всплывющих элементов',
event_props : 'События',
advanced_props : 'Расширенные настройки',
popup_opts : 'Опции',
anchor_names : 'Якоря',
target_same : 'Открывать в этом окне / фрейме',
target_parent : 'Открывать в родительском окне / фрейме',
target_top : 'Открывать в верхнем фрейме (заменять все фреймы)',
target_blank : 'Открывать в новом окне',
popup : 'Всплывающее окно Javascript',
popup_url : 'Всплывающий URL',
popup_name : 'Имя окна',
popup_return : 'Вставить \'return false\'',
popup_scrollbars : 'Показывать линейки прокрутки',
popup_statusbar : 'Показывать строку состояния',
popup_toolbar : 'Показывать панели инструментов',
popup_menubar : 'Показывать панель меню',
popup_location : 'Показывать панель расположения',
popup_resizable : 'Позволить изменять размеры окна',
popup_dependent : 'Зависимость (только Mozilla/Firefox)',
popup_size : 'Размер',
popup_position : 'Расположение (X/Y)',
id : 'Id',
style: 'Стиль',
classes : 'Классы',
target_name : 'Имя цели',
langdir : 'Направление письма в языке',
target_langcode : 'Целевой язык',
langcode : 'Код языка',
encoding : 'Целевая кодировка',
mime : 'Целевой MIME тип',
rel : 'Зависимость страница -> цель',
rev : 'Зависимость цель -> страница',
tabindex : 'Индекс таблицы',
accesskey : 'Ключ доступа',
ltr : 'Слева направо',
rtl : 'Справа налево'
}}});
tinyMCE.addI18n( {ru : { advlink_dlg : {
    title:"Insert/edit link",
    url:"Link URL",
    target:"Target",
    titlefield:"Title",
    is_email:"The URL you entered seems to be an email address, do you want to add the required mailto: prefix?",
    is_external:"The URL you entered seems to external link, do you want to add the required http:// prefix?",
    list:"Link list",
    general_tab:"General",
    popup_tab:"Popup",
    events_tab:"Events",
    advanced_tab:"Advanced",
    general_props:"General properties",
    popup_props:"Popup properties",
    event_props:"Events",
    advanced_props:"Advanced properties",
    popup_opts:"Options",
    anchor_names:"Anchors",
    target_same:"Open in this window / frame",
    target_parent:"Open in parent window / frame",
    target_top:"Open in top frame (replaces all frames)",
    target_blank:"Open in new window",
    popup:"Javascript popup",
    popup_url:"Popup URL",
    popup_name:"Window name",
    popup_return:"Insert 'return false'",
    popup_scrollbars:"Show scrollbars",
    popup_statusbar:"Show status bar",
    popup_toolbar:"Show toolbars",
    popup_menubar:"Show menu bar",
    popup_location:"Show location bar",
    popup_resizable:"Make window resizable",
    popup_dependent:"Dependent (Mozilla/Firefox only)",
    popup_size:"Size",
    popup_position:"Position (X/Y)",
    id:"Id",
    style:"Style",
    classes:"Classes",
    target_name:"Target name",
    langdir:"Language direction",
    target_langcode:"Target language",
    langcode:"Language code",
    encoding:"Target character encoding",
    mime:"Target MIME type",
    rel:"Relationship page to target",
    rev:"Relationship target to page",
    tabindex:"Tabindex",
    accesskey:"Accesskey",
    ltr:"Left to right",
    rtl:"Right to left",
    link_list:"Link list"
}}});
